=== VeryGoodTravel/vgt-web-app/src/schemas/responses/TravelFilters.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "TravelFilters.schema.json",
  "title": "TravelFilters",
  "description": "Travel filters describing available options to be displayed in search bar.",
  "type": "object",
  "properties": {
    "origins": {
      "description": "Available places of departure.",
      "type": "array",
      "items": {
        "$ref": "TravelLocation.schema.json"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "destinations": {
      "description": "Available tour destinations",
      "type": "array",
      "items": {
        "$ref": "TravelLocation.schema.json"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "dates": {
      "description": "Date range of available tours.",
      "$ref": "TravelDateRange.schema.json"
    },
    "participants": {
      "description": "Participants types based on their age.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "label": {
            "type": "string"
          },
          "min": {
            "type": "integer",
            "minimum": 0
          },
          "max": {
            "type": "integer",
            "minimum": 0
          }
        },
        "required": [
          "id",
          "label",
          "min",
          "max"
        ]
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": [
    "origins",
    "destinations",
    "dates",
    "participants"
  ]
}

=== VeryGoodTravel/vgt-web-app/src/schemas/responses/examples/TravelFilters.example.json
{
  "origins": [
    {
      "id": "1",
      "label": "Polska",
      "locations": [
        {
          "id": "2",
          "label": "Warszawa"
        },
        {
          "id": "6",
          "label": "Gdańsk"
        }
      ]
    }
  ],
  "destinations": [
    {
      "id": "3",
      "label": "Wielka Brytania",
      "locations": [
        {
          "id": "4",
          "label": "Londyn"
        },
        {
          "id": "5",
          "label": "Birmingham"
        }
      ]
    }
  ],
  "dates": {
    "from": "01-04-2024",
    "to": "31-04-2024"
  },
  "participants": [
    {
      "id": "1",
      "label": "Dorośli",
      "min": 1,
      "max": 4
    },
    {
      "id": "2",
      "label": "Dzieci 0-3 lat",
      "min": 0,
      "max": 4
    },
    {
      "id": "3",
      "label": "Dzieci 4-10 lat",
      "min": 0,
      "max": 4
    },
    {
      "id": "4",
      "label": "Dzieci 11-18 lat",
      "min": 0,
      "max": 4
    }
  ]
}
