=== VeryGoodTravel/vgt-web-app/src/schemas/responses/TravelOffer.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "TravelOffer.schema.json",
  "title": "TravelOffer",
  "description": "Describes single tour offer including its availability.",
  "type": "object",
  "properties": {
    "origin": {
      "$ref": "TravelLocation.schema.json"
    },
    "destination": {
      "$ref": "TravelLocation.schema.json"
    },
    "date": {
      "$ref": "TravelDateRange.schema.json"
    },
    "price": {
      "type": "object",
      "properties": {
        "value": {
          "type": "number",
          "minimum": 0.0
        },
        "currency": {
          "type": "string"
        }
      },
      "required": [
        "value",
        "currency"
      ]
    },
    "availability": {
      "$comment": "If not provided, defaults to false",
      "type": "boolean"
    },
    "rating": {
      "$comment": "If not provided, defaults to 0.0",
      "type": "number",
      "minimum": 0.0,
      "maximum": 5.0
    },
    "image": {
      "$ref": "TravelImage.schema.json"
    }
  },
  "required": [
    "origin",
    "destination",
    "date",
    "price"
  ]
}

=== VeryGoodTravel/vgt-web-app/src/schemas/responses/examples/TravelOffer.example.json
{
  "origin": {
    "id": "1",
    "label": "Warszawa"
  },
  "destination": {
    "id": "2",
    "label": "Londyn"
  },
  "date": {
    "from": "01-04-2024",
    "to": "04-04-2024"
  },
  "price": {
    "value": 300.0,
    "currency": "z≈Ç"
  },
  "rating": 4.4,
  "availability": true,
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAIAQMAAAD+wSzIAAAABlBMVEX///+/v7+jQ3Y5AAAADklEQVQI12P4AIX8EAgALgAD/aNpbtEAAAAASUVORK5CYII"
}
